compute an inversion of the matrix

In [18]:
import numpy as np

In [19]:
matrix = np.array([[1, 0.2,0.5],
                   [0.2,1,0.8],
                   [0.5,0.8,1]])

In [20]:
transpose_matrix = np.transpose(matrix)

In [21]:
print("Original Matrix:")
print(matrix)
print("\nTranspose of the Matrix:")
print(transpose_matrix)

Original Matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]

Transpose of the Matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


(b) the determinant

In [22]:
import numpy as np

In [23]:
matrix = np.array([[1, 0.2,0.5],
                   [0.2,1,0.8],
                   [0.5,0.8,1]])

In [24]:
determinant = np.linalg.det(matrix)

In [25]:
print("Matrix:")
print(matrix)

print("\nDeterminant of the Matrix:", determinant)

Matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]

Determinant of the Matrix: 0.2299999999999999


 (c)decompose the matrix

In [26]:
import numpy as np
import scipy.linalg


In [27]:
matrix = np.array([[1, 0.2,0.5],
                   [0.2,1,0.8],
                   [0.5,0.8,1]])

In [28]:
P, L, U = scipy.linalg.lu(matrix)

In [29]:
print("Matrix:")
print(matrix)

Matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [30]:
print("\nPermutation Matrix (P):")
print(P)


Permutation Matrix (P):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
print("\nLower Triangular Matrix (L):")
print(L)

print("\nUpper Triangular Matrix (U):")
print(U)


Lower Triangular Matrix (L):
[[1.         0.         0.        ]
 [0.2        1.         0.        ]
 [0.5        0.72916667 1.        ]]

Upper Triangular Matrix (U):
[[1.         0.2        0.5       ]
 [0.         0.96       0.7       ]
 [0.         0.         0.23958333]]


(d) transform the matrix

In [32]:
import numpy as np

In [ ]:
matrix = np.array([[1, 0.2,0.5],
                   [0.2,1,0.8],
                   [0.5,0.8,1]])